### ISSUE TITLE
Create basic URL Predictor

### ISSUE THREAD

**Issue by MaximilianJRichter** [jamchu1/KGLab_WS2022#10]
take website of latest event of a series and if it contains the year the event took place, predict a new website by replacing the year by others. Then check if the predicted website exists (status code 200).

**Comment by WolfgangFahl** [comment]
Again please specify one or more  concrete scenarios as acceptance criteria

**Comment by jamchu1** [comment]
The URL Predictor checks whether the predicted website exists and is accessible (HTTP status code 200).

**Comment by jamchu1** [comment]
The URL Predictor checks whether the predicted website exists and is accessible (HTTP status code 200).

**Comment by WolfgangFahl** [comment]
How can the given task be solved with out this?
